### ISSUE TITLE
Easy way to limit chip amount?

### ISSUE THREAD

**Issue by behelit** [AndroidDeveloperLB/ChipsLibrary#4]
Is there an easy way to limit the number of chips to 1?
Maybe by preventing any results from being returned if the chip count is > x

**Comment by AndroidDeveloperLB** [comment]
Yes, but it's not a part of the API there (or at least I don't think it is). 
All I did here is to import Google's code, and fix some issues in it to make it work, so you need to dive in the code to check how to do it.
Maybe they've updated their code since I've done it. Sorry.

**Comment by behelit** [comment]
Haha yes thanks, I guess I was just checking before I go rewriting the code.
I was able to do it by turning off the tokenizer once a chip was detected.

Your code is really helpful compared to the google source!

**Comment by AndroidDeveloperLB** [comment]
It was made a long time ago. It might still have bugs,  because it's
heavily based on Google's code
